development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: Meetin_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  # url: <%= ENV.fetch("REDIS_URL") { Rails.env == 'development' ? "redis://localhost:6379/1" : "redis://meet-in.herokuapp.com:6379/1"} %>
